### ISSUE TITLE
Can't open form ui quest

### ISSUE THREAD

**Issue by chisi21** [jaylac2000/Quests#2]
the plugin is enabled, but when typing /quest, the form ui does not appear

**Comment by jaylac2000** [comment]
i will try and see the issue

**Comment by jaylac2000** [comment]
Ok, try again but for now use this http://www.mediafire.com/file/86ewh0005akn4xa/file

**Comment by jaylac2000** [comment]
dev 16 should also work. i cannot release it until the current dev release is approved that i tried to release
